{{- if eq .Values.secrets.mode "create" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "millionsend.secretName" . }}
  labels:
    {{- include "millionsend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.create.data }}
  {{ $k }}: {{ toString $v | quote }}
  {{- end }}
{{- end }}
