// Pure list, safe to import from client components (no db or node imports).
export const AUDIT_ACTIONS = [
  "api_key.created",
  "api_key.revoked",
  "api_key.renamed",
  "domain.created",
  "domain.verified",
  "domain.deleted",
  "webhook.created",
  "webhook.updated",
  "webhook.secret_rotated",
  "webhook.deleted",
  "member.invited",
  "member.joined",
  "member.removed",
  "member.role_changed",
  "member.left",
  "invitation.revoked",
  "invitation.resent",
  "team.created",
  "team.deleted",
  "team.type_changed",
  "team.limits_updated",
  "team.broadcasts_paused",
  "team.broadcasts_resumed",
  "team.suspended",
  "team.reinstated",
  "console.flag_opened",
  "console.flag_cleared",
  "console.flag_reopened",
  "region.breaker_opened",
  "region.breaker_closed",
  "region.quota_requested",
  "instance.settings_updated",
  "billing.checkout_started",
  "billing.portal_opened",
  "billing.subscription_updated",
  "billing.plan_changed",
  "billing.overage_toggled",
] as const;
export type AuditAction = (typeof AUDIT_ACTIONS)[number];
