// Pure list, safe to import from client components (no db or node imports).
export const AUDIT_ACTIONS = [
  "api_key.created",
  "api_key.revoked",
  "api_key.renamed",
  "domain.created",
  "domain.verified",
  "domain.deleted",
  "webhook.created",
  "webhook.updated",
  "webhook.secret_rotated",
  "webhook.deleted",
  "member.invited",
  "member.joined",
  "member.removed",
  "member.role_changed",
  "member.left",
  "invitation.revoked",
  "invitation.resent",
  "team.created",
  "team.deleted",
  "team.type_changed",
  "team.limits_updated",
  "team.broadcasts_paused",
  "team.broadcasts_resumed",
  "team.suspended",
  "team.reinstated",
  // The content monitor's review hold: a suspension the team reads as a pause.
  "team.held_for_review",
  "team.ses_tenant_updated",
  "team.ses_tenant_update_failed",
  // The instance side of a break-glass content access (team_id null, so the
  // team's own audit can never show it); "content.accessed" is the row the
  // team gains seven days later, dated at the access.
  "content.revealed",
  "content.accessed",
  "console.flag_opened",
  "console.flag_cleared",
  "console.flag_reopened",
  "region.breaker_opened",
  "region.breaker_closed",
  "region.quota_requested",
  "instance.settings_updated",
  "instance.monitor_settings_updated",
  "instance.reserve_updated",
  "monitor.override_set",
  "monitor.override_cleared",
  "monitor.broadcasts_paused",
  "monitor.broadcasts_resumed",
  "support.view_started",
  "support.view_ended",
  "billing.checkout_started",
  "billing.portal_opened",
  "billing.subscription_updated",
  "billing.plan_changed",
  "billing.overage_toggled",
] as const;
export type AuditAction = (typeof AUDIT_ACTIONS)[number];
