export {
  assertEnvConsistency,
  EMAIL_RETENTION_DAYS_DEFAULT,
  type Env,
  env,
  isCloudDeployment,
  notificationsEmailFrom,
  OPEN_PREFETCH_WINDOW_SECONDS_DEFAULT,
  parseCommaList,
  parseEmailFrom,
  parseSnsTopicArns,
  SES_MAX_SEND_RATE_DEFAULT,
  sesTenantsEnabled,
  trackingCnameTarget,
  trackingSubdomainsSupported,
} from "./env.js";
