import type { McpScope } from "@millionsend/core";

/* Mirror of the tool registry in apps/api/src/mcp.ts — the API is the
   source of truth; test/mcp-tools-sync.test.ts fails when they drift. */
export const MCP_TOOLS: { name: string; scope: McpScope; readOnly?: boolean }[] = [
  { name: "list_emails", scope: "emails:read", readOnly: true },
  { name: "get_email", scope: "emails:read", readOnly: true },
  { name: "get_email_insights", scope: "emails:read", readOnly: true },
  { name: "get_deliverability", scope: "emails:read", readOnly: true },
  { name: "get_usage", scope: "emails:read", readOnly: true },
  { name: "list_contacts", scope: "audience:read", readOnly: true },
  { name: "get_contact", scope: "audience:read", readOnly: true },
  { name: "get_contact_topics", scope: "audience:read", readOnly: true },
  { name: "list_segments", scope: "audience:read", readOnly: true },
  { name: "get_segment", scope: "audience:read", readOnly: true },
  { name: "list_topics", scope: "audience:read", readOnly: true },
  { name: "get_topic", scope: "audience:read", readOnly: true },
  { name: "list_contact_properties", scope: "audience:read", readOnly: true },
  { name: "list_suppressions", scope: "audience:read", readOnly: true },
  { name: "get_suppression", scope: "audience:read", readOnly: true },
  { name: "list_broadcasts", scope: "broadcasts:read", readOnly: true },
  { name: "get_broadcast", scope: "broadcasts:read", readOnly: true },
  { name: "list_templates", scope: "templates:read", readOnly: true },
  { name: "get_template", scope: "templates:read", readOnly: true },
  { name: "list_webhooks", scope: "webhooks:write", readOnly: true },
  { name: "get_webhook", scope: "webhooks:write", readOnly: true },
  { name: "list_api_keys", scope: "api-keys:write", readOnly: true },
  { name: "list_domains", scope: "domains:read", readOnly: true },
  { name: "get_domain", scope: "domains:read", readOnly: true },
  { name: "send_email", scope: "emails:send" },
  { name: "send_email_batch", scope: "emails:send" },
  { name: "update_email", scope: "emails:send" },
  { name: "cancel_email", scope: "emails:send" },
  { name: "create_contact", scope: "audience:write" },
  { name: "create_contact_batch", scope: "audience:write" },
  { name: "update_contact", scope: "audience:write" },
  { name: "update_contact_topics", scope: "audience:write" },
  { name: "delete_contact", scope: "audience:write" },
  { name: "add_contact_to_segment", scope: "audience:write" },
  { name: "remove_contact_from_segment", scope: "audience:write" },
  { name: "create_segment", scope: "audience:write" },
  { name: "update_segment", scope: "audience:write" },
  { name: "delete_segment", scope: "audience:write" },
  { name: "create_topic", scope: "audience:write" },
  { name: "update_topic", scope: "audience:write" },
  { name: "delete_topic", scope: "audience:write" },
  { name: "create_contact_property", scope: "audience:write" },
  { name: "update_contact_property", scope: "audience:write" },
  { name: "delete_contact_property", scope: "audience:write" },
  { name: "add_suppressions", scope: "audience:write" },
  { name: "remove_suppressions", scope: "audience:write" },
  { name: "delete_suppression", scope: "audience:write" },
  { name: "create_broadcast", scope: "broadcasts:write" },
  { name: "update_broadcast", scope: "broadcasts:write" },
  { name: "send_broadcast", scope: "broadcasts:write" },
  { name: "cancel_broadcast", scope: "broadcasts:write" },
  { name: "delete_broadcast", scope: "broadcasts:write" },
  { name: "create_template", scope: "templates:write" },
  { name: "update_template", scope: "templates:write" },
  { name: "delete_template", scope: "templates:write" },
  { name: "create_webhook", scope: "webhooks:write" },
  { name: "update_webhook", scope: "webhooks:write" },
  { name: "delete_webhook", scope: "webhooks:write" },
  { name: "create_api_key", scope: "api-keys:write" },
  { name: "revoke_api_key", scope: "api-keys:write" },
  { name: "create_domain", scope: "domains:write" },
  { name: "update_domain", scope: "domains:write" },
  { name: "verify_domain", scope: "domains:write" },
  { name: "delete_domain", scope: "domains:write" },
];
